sudo: required

language: go

go: 
  - "1.10"

services:
  - docker

before_install:
  - docker-compose up -d

install:
  - apt-get update && apt-get install postgresql-client -y

script:
  - go version
  - psql --version