sudo: required

language: go

go: 
  - "1.10"

services:
  - docker

before_install:
  - docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -p 127.0.0.1:5432:5432 -d postgres

install:
  - apt-get update && apt-get install postgresql-client -y

script:
  - go version
  - psql --version