version: '3'

services:
  db-service:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    # ports:  ## uncomment for local debug
    #   - 5432:5432
      
  rest-api-service:
    build: .
    volumes:
      - .:/simple-go-rest-api
    ports:
      - 127.0.0.1:5002:5002
    depends_on:
      - db-service
